import type { Locale } from '../i18n/locales';

const enUS = {
  'action.addingLocalFiles': 'Adding...',
  'action.addLocalFiles': 'Add local songs',
  'action.changeCover': 'Change playlist cover',
  'action.resetCover': 'Restore default cover',
  'confirm.delete': 'Delete playlist "{name}"?',
  'error.exportUnavailable': 'Playlist export is currently unavailable.',
  'error.importUnavailable': 'Playlist file import is currently unavailable.',
  'error.smartUnavailable': 'Smart playlist generation is currently unavailable.',
  'menu.aria': 'More playlist actions',
  'menu.export': 'Export playlist',
  'menu.rename': 'Rename playlist',
  'menu.sort': 'Sort order',
  'prompt.rename': 'Rename playlist',
  'smart.subtitle': 'Based on recent and frequently played songs',
  'smart.title': 'Smart generate',
  'sort.addedDesc': 'Recently added',
  'sort.artistAsc': 'Artist A-Z',
  'sort.manual': 'Manual order',
  'sort.titleAsc': 'Title A-Z',
  'sort.titleDesc': 'Title Z-A',
  'status.addedToPlaylist': 'Added to playlist: {name}',
  'status.coverReset': 'Restored the default playlist cover',
  'status.coverUpdated': 'Playlist cover updated',
  'status.exported': 'Playlist exported: {path}',
  'status.generatedSmart': 'Smart playlist created: {name} ({count} songs)',
  'status.generatingSmart': 'Generating a playlist from recent listening...',
  'status.importedFile': 'Playlist imported: {name} ({count} songs)',
  'status.itemMoved': 'Playlist order saved',
  'status.itemRemoved': 'Removed from playlist: {title}',
  'status.nameCopied': 'Song title and artist copied',
  'status.pathCopied': 'File path copied',
  'status.queued': 'Added to queue: {title}',
  'status.queuedNext': 'Playing next: {title}',
  'status.renamed': 'Playlist renamed',
  'status.sortUpdated': 'Sort order updated',
} as const;

export type SteamPlaylistTextKey = keyof typeof enUS;
type SteamPlaylistTextDictionary = Record<SteamPlaylistTextKey, string>;
type SteamPlaylistTextOptions = Record<string, string | number>;

const translations: Record<Locale, SteamPlaylistTextDictionary> = {
  'en-US': enUS,
  'zh-CN': {
    'action.addingLocalFiles': '添加中...',
    'action.addLocalFiles': '添加本地歌曲',
    'action.changeCover': '更换歌单封面',
    'action.resetCover': '恢复默认封面',
    'confirm.delete': '删除歌单“{name}”？',
    'error.exportUnavailable': '歌单导出功能暂不可用。',
    'error.importUnavailable': '歌单文件导入功能暂不可用。',
    'error.smartUnavailable': '智能歌单生成功能暂不可用。',
    'menu.aria': '更多歌单操作',
    'menu.export': '导出歌单',
    'menu.rename': '重命名歌单',
    'menu.sort': '排序方式',
    'prompt.rename': '重命名歌单',
    'smart.subtitle': '根据最近常听与历史高频生成',
    'smart.title': '智能生成',
    'sort.addedDesc': '最近添加',
    'sort.artistAsc': '艺术家 A-Z',
    'sort.manual': '手动排序',
    'sort.titleAsc': '歌名 A-Z',
    'sort.titleDesc': '歌名 Z-A',
    'status.addedToPlaylist': '已加入歌单：{name}',
    'status.coverReset': '已恢复默认歌单封面',
    'status.coverUpdated': '歌单封面已更新',
    'status.exported': '歌单已导出：{path}',
    'status.generatedSmart': '已生成智能歌单：{name}（{count} 首）',
    'status.generatingSmart': '正在根据最近常听生成歌单...',
    'status.importedFile': '已导入歌单：{name}，共 {count} 首',
    'status.itemMoved': '歌单顺序已保存',
    'status.itemRemoved': '已从歌单移除：{title}',
    'status.nameCopied': '歌名与艺术家已复制',
    'status.pathCopied': '文件路径已复制',
    'status.queued': '已添加到队列：{title}',
    'status.queuedNext': '下一首播放：{title}',
    'status.renamed': '歌单已重命名',
    'status.sortUpdated': '排序方式已更新',
  },
  'zh-TW': {
    'action.addingLocalFiles': '加入中...',
    'action.addLocalFiles': '加入本機歌曲',
    'action.changeCover': '更換歌單封面',
    'action.resetCover': '恢復預設封面',
    'confirm.delete': '刪除歌單「{name}」？',
    'error.exportUnavailable': '歌單匯出功能目前無法使用。',
    'error.importUnavailable': '歌單檔案匯入功能目前無法使用。',
    'error.smartUnavailable': '智慧歌單生成功能目前無法使用。',
    'menu.aria': '更多歌單操作',
    'menu.export': '匯出歌單',
    'menu.rename': '重新命名歌單',
    'menu.sort': '排序方式',
    'prompt.rename': '重新命名歌單',
    'smart.subtitle': '根據最近常聽與歷史高頻歌曲生成',
    'smart.title': '智慧生成',
    'sort.addedDesc': '最近加入',
    'sort.artistAsc': '藝人 A-Z',
    'sort.manual': '手動排序',
    'sort.titleAsc': '歌名 A-Z',
    'sort.titleDesc': '歌名 Z-A',
    'status.addedToPlaylist': '已加入歌單：{name}',
    'status.coverReset': '已恢復預設歌單封面',
    'status.coverUpdated': '歌單封面已更新',
    'status.exported': '歌單已匯出：{path}',
    'status.generatedSmart': '已建立智慧歌單：{name}（{count} 首）',
    'status.generatingSmart': '正在根據最近聆聽生成歌單...',
    'status.importedFile': '已匯入歌單：{name}，共 {count} 首',
    'status.itemMoved': '歌單順序已儲存',
    'status.itemRemoved': '已從歌單移除：{title}',
    'status.nameCopied': '歌名與藝人已複製',
    'status.pathCopied': '檔案路徑已複製',
    'status.queued': '已加入佇列：{title}',
    'status.queuedNext': '下一首播放：{title}',
    'status.renamed': '歌單已重新命名',
    'status.sortUpdated': '排序方式已更新',
  },
  'ja-JP': {
    'action.addingLocalFiles': '追加中...',
    'action.addLocalFiles': 'ローカル曲を追加',
    'action.changeCover': 'プレイリストのカバーを変更',
    'action.resetCover': '既定のカバーに戻す',
    'confirm.delete': 'プレイリスト「{name}」を削除しますか？',
    'error.exportUnavailable': 'プレイリストの書き出しは現在利用できません。',
    'error.importUnavailable': 'プレイリストファイルの取り込みは現在利用できません。',
    'error.smartUnavailable': 'スマートプレイリスト生成は現在利用できません。',
    'menu.aria': 'その他のプレイリスト操作',
    'menu.export': 'プレイリストを書き出す',
    'menu.rename': 'プレイリスト名を変更',
    'menu.sort': '並び順',
    'prompt.rename': 'プレイリスト名を変更',
    'smart.subtitle': '最近よく聴いた曲と再生頻度から生成',
    'smart.title': 'スマート生成',
    'sort.addedDesc': '最近追加した順',
    'sort.artistAsc': 'アーティスト A-Z',
    'sort.manual': '手動並べ替え',
    'sort.titleAsc': '曲名 A-Z',
    'sort.titleDesc': '曲名 Z-A',
    'status.addedToPlaylist': 'プレイリストに追加しました：{name}',
    'status.coverReset': '既定のプレイリストカバーに戻しました',
    'status.coverUpdated': 'プレイリストのカバーを更新しました',
    'status.exported': 'プレイリストを書き出しました：{path}',
    'status.generatedSmart': 'スマートプレイリストを作成しました：{name}（{count} 曲）',
    'status.generatingSmart': '最近の再生履歴からプレイリストを生成しています...',
    'status.importedFile': 'プレイリストを取り込みました：{name}（{count} 曲）',
    'status.itemMoved': 'プレイリストの順序を保存しました',
    'status.itemRemoved': 'プレイリストから削除しました：{title}',
    'status.nameCopied': '曲名とアーティストをコピーしました',
    'status.pathCopied': 'ファイルパスをコピーしました',
    'status.queued': 'キューに追加しました：{title}',
    'status.queuedNext': '次に再生：{title}',
    'status.renamed': 'プレイリスト名を変更しました',
    'status.sortUpdated': '並び順を更新しました',
  },
  'ko-KR': {
    'action.addingLocalFiles': '추가 중...',
    'action.addLocalFiles': '로컬 곡 추가',
    'action.changeCover': '재생목록 표지 변경',
    'action.resetCover': '기본 표지로 복원',
    'confirm.delete': '재생목록 "{name}"을(를) 삭제할까요?',
    'error.exportUnavailable': '현재 재생목록 내보내기를 사용할 수 없습니다.',
    'error.importUnavailable': '현재 재생목록 파일 가져오기를 사용할 수 없습니다.',
    'error.smartUnavailable': '현재 스마트 재생목록 생성을 사용할 수 없습니다.',
    'menu.aria': '더 많은 재생목록 작업',
    'menu.export': '재생목록 내보내기',
    'menu.rename': '재생목록 이름 바꾸기',
    'menu.sort': '정렬 방식',
    'prompt.rename': '재생목록 이름 바꾸기',
    'smart.subtitle': '최근 및 자주 재생한 곡을 기반으로 생성',
    'smart.title': '스마트 생성',
    'sort.addedDesc': '최근 추가순',
    'sort.artistAsc': '아티스트 A-Z',
    'sort.manual': '수동 정렬',
    'sort.titleAsc': '제목 A-Z',
    'sort.titleDesc': '제목 Z-A',
    'status.addedToPlaylist': '재생목록에 추가됨: {name}',
    'status.coverReset': '기본 재생목록 표지로 복원됨',
    'status.coverUpdated': '재생목록 표지가 업데이트됨',
    'status.exported': '재생목록 내보냄: {path}',
    'status.generatedSmart': '스마트 재생목록 생성됨: {name} ({count}곡)',
    'status.generatingSmart': '최근 재생 기록으로 재생목록 생성 중...',
    'status.importedFile': '재생목록 가져옴: {name} ({count}곡)',
    'status.itemMoved': '재생목록 순서가 저장됨',
    'status.itemRemoved': '재생목록에서 제거됨: {title}',
    'status.nameCopied': '곡 제목과 아티스트를 복사함',
    'status.pathCopied': '파일 경로를 복사함',
    'status.queued': '대기열에 추가됨: {title}',
    'status.queuedNext': '다음 재생: {title}',
    'status.renamed': '재생목록 이름이 변경됨',
    'status.sortUpdated': '정렬 방식이 업데이트됨',
  },
};

export const steamPlaylistText = (
  locale: Locale,
  key: SteamPlaylistTextKey,
  options?: SteamPlaylistTextOptions,
): string => {
  const text = translations[locale][key] ?? enUS[key];
  if (!options) {
    return text;
  }
  return text.replace(/\{(\w+)\}/gu, (match, token: string) => String(options[token] ?? match));
};
