/**
 * Generated by `npm run sync:contributors` from GitHub's contributors API.
 * Do not edit this file directly; use contributors.config.json for additions
 * and exclusions that are not represented by repository commits.
 */
export const githubContributorIds = [
  'Moekotori',
  'ChunchunOwO',
  'XUN07210721',
  'zpf2234',
  'bailuoqi',
  'fy-hb',
  'YuMinSaMa',
  'Znfooe',
  'chara0618',
] as const;
