import contributorConfig from './contributors.config.json';
import { githubContributorIds } from './contributors.github.generated';

const blockedContributorIds = new Set(
  contributorConfig.blacklist.map((id) => id.toLocaleLowerCase('en-US')),
);

/**
 * Contributor IDs shown in Settings -> About -> Contributors.
 *
 * GitHub commit contributors are generated by `npm run sync:contributors`.
 * Add non-code contributors and permanent exclusions in contributors.config.json.
 */
export const contributorIds = [...githubContributorIds, ...contributorConfig.additionalContributorIds]
  .filter((id, index, ids) => {
    const normalizedId = id.toLocaleLowerCase('en-US');
    return !blockedContributorIds.has(normalizedId)
      && ids.findIndex((candidate) => candidate.toLocaleLowerCase('en-US') === normalizedId) === index;
  });

